### PR TITLE
Display simple download status in web UI

### PR DESCRIPTION
**Pull request by DevEmilio96**
Non-infinite pooling, it is activated only when the user sends a message, and stops either when the page is refreshed or when the download finishes

Issue : #250

### CODE REVIEW

**Comment by AlexCheema** [comment]
Great job with this. I've added a retrospective $100 bounty for this as I think it deserves it. Stuff like this is really important for UX.

One annoying thing about this behaviour is the first time you use exo when the model is not downloaded, the request times out and you see nothing.
What would make this really nice from a UX perspective is to automatically retry the request once the download completes.

**Comment by DevEmilio96** [comment]
Thank you for the bounty, but it’s not necessary – I appreciate the gesture though!

Just a quick reminder, we have a call scheduled for Thursday at 4:00 PM. I’ll also make sure to add the other modification you requested regarding the behavior of the model download.

**Comment by AlexCheema** [comment]
Just ping me when you've resolved conflicts + fixed the retry.
This is a really valuable QoL PR I'd like to get merged for all the new users that are trying out exo.

**Comment by DevEmilio96** [comment]
Hi @AlexCheema, I’ve resolved all the conflicts, and everything should be good to go now. I’ll handle the "fixed the retry" modification in a separate commit, so you can go ahead and merge the changes related to this PR.

**Pull request merged**
