### PR TITLE
Vision Llama, Pixtral support and Vision integration test

### PR DESCRIPTION
**Pull request by varshith15**
https://github.com/exo-explore/exo/issues/215
https://github.com/exo-explore/exo/issues/247
https://github.com/exo-explore/exo/issues/328

### CODE REVIEW

**Comment by AlexCheema** [comment]
Putting this on hold for now while we re-prioritise. Will pay out the bounty now for all this great work and revisit later. Please send me an email alex@exolabs.net to claim the bounty.

**Comment by jackzampolin** [comment]
looking to use the llama 3.2 11b model as well and wondering what the timeline on this is?

**Comment by winstondu** [comment]
@AlexCheema @varshith15 ?

**Comment by varshith15** [comment]
@jackzampolin @winstondu you can use this branch as is, it works as expected

**Pull request closed without merging**
