### PR TITLE
Improved clarity, fixed typos, added macOS/Linux examples, and enhanc…

### PR DESCRIPTION
**Pull request by VerisimilitudeX**

### CODE REVIEW

**Comment by VerisimilitudeX** [comment]
@xeb @jshield @wbic16 @mattroyer could you please take a look?

**Comment by jshield** [comment]
I'd probably phrase the macOS python line as:

On certain versions of Python on macOS, certificates may not be installed correctly, potentially causing SSL errors (e.g., when accessing huggingface.co). To resolve this, run the 'Install Certificates' command, typically as follows:

but otherwise LGTM

**Comment by VerisimilitudeX** [comment]
Perfect! @jshield, I updated it.

**Comment by AlexCheema** [comment]
LGTM! Thank you!

**Pull request merged**
