### PR TITLE
Ignore binary messages from MikroTik routers

### PR DESCRIPTION
**Pull request by xeb**
Works on my machines!

This will ignore any MikroTik (or any other binary messages) during discovery and only process those messages that are valid JSON

### CODE REVIEW

**Comment by AlexCheema** [comment]
Awesome - just what we needed!

Can we make the json validation a bit more robust by trying to parse the json and catching the exception

**Comment by AlexCheema** [comment]
Bump @xeb

**Comment by AlexCheema** [comment]
Looks good. Removed the accidentally added files.

**Comment by xeb** [comment]
Oops! Sorry about that :) 

you’re awesome, thanks!

**Pull request merged**
