### PR TITLE
only load layers in shard in tinygrad

### PR DESCRIPTION
**Pull request by roryclear**
I've been running out of mem as it's currently loading all the weights in a model

### CODE REVIEW

**Comment by AlexCheema** [comment]
I'm surprised this helps.
Did you check memory usage before and after your changes?

**Comment by roryclear** [comment]
> I'm surprised this helps. Did you check memory usage before and after your changes?

yeah on my phone I can't even run 1B without something like this, all the weights load and it crashes.
This is part of 3B for example
main:
Screenshot 2024-11-28 at 11 40 52
with change:
Screenshot 2024-11-28 at 11 41 57

**Comment by AlexCheema** [comment]
Great work, please email alex@exolabs.net for $100 retrospective bounty.

**Comment by roryclear** [comment]
> Great work, please email [alex@exolabs.net](mailto:alex@exolabs.net) for $100 retrospective bounty.

did you forget to send this? or I sent the wrong address

**Pull request merged**
